image: docker:latest
services:
  - docker:dind

stages:
  - build

lint:
  stage: build
  image: golangci/golangci-lint:latest-alpine
  script:
    - golangci-lint run -v --timeout 2m --out-format tab -c .golangci.yml
  allow_failure: true

test:
  stage: build
  image: golang:1.14
  script:
    - go test -mod=readonly -race -v ./...

verify:
  stage: build
  script:
    - apk update && apk add git
    - ./verify.sh
  only:
    - branches
  except:
    - master
