image: docker:latest
services:
  - docker:dind

stages:
  - build

lint:
  stage: build
  image: golangci/golangci-lint:v1.32.2-alpine
  script:
    - apk --no-cache add git jq
    # Write the code coverage report to gl-code-quality-report.json
    # and print linting issues to stdout in the format: path/to/file:line description
    - golangci-lint run -v --timeout 2m --out-format code-climate -c .golangci.yml | tee gl-code-quality-report.json | jq -r '.[] | "\(.location.path):\(.location.lines.begin) \(.description)"'
  artifacts:
    reports:
      codequality: gl-code-quality-report.json
    paths:
      - gl-code-quality-report.json

test:
  stage: build
  image: golang:1.14
  script:
    - go test -mod=readonly -race -v ./...

verify:
  stage: build
  script:
    - apk update && apk add git
    - ./verify.sh
  only:
    - branches
  except:
    - master
